# backend/app/schema.py

# Import BaseModel from pydantic. This is the core class we use to create
# strict data schemas. Any class inheriting from BaseModel will automatically
# validate incoming or outgoing data.
from pydantic import BaseModel

# Import Optional from typing. This is used for fields that might not always
# be present or might be empty (e.g., a WhatsApp link is only sent if needed).
from typing import Optional

# ==========================================
# 1. THE INCOMING DATA (Request from React)
# ==========================================

# We define a class named ChatRequest to validate what React sends us.
# When a user hits "Send" on the widget, this model checks the payload.
class ChatRequest(BaseModel):
    
    # We expect exactly one key named 'message' and its value MUST be a string.
    # If the frontend sends {"text": "hello"} instead of {"message": "hello"},
    # Pydantic will instantly block it and return a 422 error, protecting our server.
    message: str

# ==========================================
# 2. THE OUTGOING DATA (Response to React)
# ==========================================

# We define a class named ChatResponse to guarantee the shape of our server's reply.
# This ensures React always knows exactly what variables it is receiving.
class ChatResponse(BaseModel):
    
    # 'reply' is the actual text generated by the Groq AI model. It must be a string.
    reply: str
    
    # 'show_whatsapp' is a boolean (True or False). Our AI will intelligently decide
    # if the user's question requires human intervention (like asking for a custom quote).
    show_whatsapp: bool
    
    # 'whatsapp_link' is an Optional string. 
    # We set its default value to None. If show_whatsapp is True, our service will 
    # populate this with your configured "wa.me/..." URL. If False, it safely stays None.
    whatsapp_link: Optional[str] = None

